local formedit = require('formedit')

vim.keymap.set('o', 'af', formedit.select.form, { desc = 'Outer form' })
vim.keymap.set('o', 'aF', formedit.select.root, { desc = 'Outer root form' })
vim.keymap.set('o', 'if', formedit.select.inner, { desc = 'Inner form' })
vim.keymap.set('o', 'iF', formedit.select['inner-root'], { desc = 'Inner root form' })
vim.keymap.set('n', '<localleader>h', formedit.insertion.head, { desc = 'Head insert' })
vim.keymap.set('n', '<localleader>H', formedit.insertion.tail, { desc = 'Tail insert' })
vim.keymap.set('n', '<localleader>i', formedit.wrap.head, { desc = 'Wrap form' })
vim.keymap.set('n', '<localleader>o', formedit.raise.form, { desc = 'Raise form' })
vim.keymap.set('n', '<localleader>O', formedit.raise.element, { desc = 'Raise element' })
vim.keymap.set('n', '>)', formedit.slurp.forward, { desc = 'Slurp forward' })
vim.keymap.set('n', '<(', formedit.slurp.backward, { desc = 'Slurp backward' })
vim.keymap.set('n', '>(', formedit.barf.backward, { desc = 'Barf backward' })
vim.keymap.set('n', '<)', formedit.barf.forward, { desc = 'Barf forward' })
